spring.application.name=matrioproject
spring.datasource.url=jdbc:h2:file:./data/matrimonydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8082
# JWT Secret Key (must be Base64 encoded)
jwt.secret=U0VjdXJlS2V5Rm9ySlNXVFNIQTI1NmJhc2U2NEVuY29kZWQhIQ==


